# Add application configuration variables here, as shown below.
GOOGLE_KEY: 268527079229.apps.googleusercontent.com
GOOGLE_SECRET: SbZ4iPgqWF4k0yZnbihlpouR

# comma seperated domains
AUTHORIZED_DOMAINS: 'ahrlty.com,wizarddevelopment.com'

# keep these blank unless you want to use s3 locally
S3_ACCESS_KEY:
S3_SECRET_KEY:
ASSET_UPLOAD_BUCKET:
ASSET_CLOUDFRONT_BUCKET: